name: Bug report / Issue
description: Report a bug or suggest an improvement for DPX repository
title: "[Issue] "
labels: [bug, help wanted]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to report a bug or suggest an improvement.

  - type: input
    id: issue-title
    attributes:
      label: Issue Title
      placeholder: "A brief title for your issue"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue or suggestion.
      placeholder: "Describe what the issue is or what feature you are suggesting"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If this is a bug report, list the steps to reproduce the issue.
      placeholder: |
        1. Step one
        2. Step two
        3. ...
      render: bash

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: "What did you expect to happen?"

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: "What actually happened?"

  - type: input
    id: environment
    attributes:
      label: Environment (OS, Python, DPX version)
      placeholder: "e.g. Windows 10, Python 3.9, DPX commit hash"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots here.
      placeholder: "Anything else you'd like to add?"
